<?php

namespace AppBundle\Repository;

/**
 * ProducttypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducttypesRepository extends \Doctrine\ORM\EntityRepository
{
}
